//--------------------------------------------------------------------------
//
// Copyright (c) 1995-1996 ChromeOcean Software - All Rights Reserved
// Reuse permission granted to Dave Thielen
//
//--------------------------------------------------------------------------

//---------------------------------------------------------------------------
//
//	Copyright (c) 1995, 1996. Windward Studios, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------


#include "stdafx.h"
#include "_windwrd.h"

#ifdef _DEBUG
#undef THIS_FILE
static char BASED_CODE THIS_FILE[] = __FILE__;
#endif
#define new DEBUG_NEW

extern const Fixed xfixSqrtTwo( 1.414213562 );
extern const Fixed xfixPI     ( 3.141592654 );
