//---------------------------------------------------------------------------
//
//	Copyright (c) 1995, 1996. Windward Studios, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------


// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//		are changed infrequently
//

#include <afxwin.h>			// MFC core and standard components
#include <afxext.h> 		// MFC extensions (including VB)
#include <afxcmn.h>
#include <afxtempl.h>
#include <afxmt.h>
#include <mmsystem.h>
#include <mmreg.h>
#include <msacm.h>

#include <limits.h>
#include <malloc.h>
#include <math.h>
#include <strstrea.h>
#include <io.h>
#include <ctl3d.h>

#include <ddraw.h>
#include <dsound.h>
//#include <dplay.h>
#include <wing.h>

#include <mssw.h>

