//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Lastplnt.rc
//
#define IDS_MAIN_TITLE                  1
#define IDS_TITLE_AREA_MAP              2
#define IDX_HELP                        3
#define IDC_MINIMIZE                    3
#define IDS_TITLE_PLAYERS               3
#define IDC_LOAD_MULTI                  4
#define IDS_TITLE_WORLD_MAP             5
#define IDS_TITLE_CHAT_WND              7
#define IDS_TITLE_BUILDINGS             8
#define IDS_TITLE_AREA_MAP_MULTI        10
#define IDS_TITLE_VEHICLES              11
#define IDH_AREA_CLOCK                  12
#define IDH_AREA_COUNTER                13
#define IDH_AREA_ZOOM_IN                14
#define IDH_AREA_ZOOM_OUT               15
#define IDB_UNIT_CENTER                 17
#define IDB_UNIT_BUILD                  18
#define IDB_UNIT_REPAIR                 19
#define IDB_UNIT_STOP                   20
#define IDB_UNIT_RETREAT                21
#define IDB_UNIT_DESTROY                22
#define IDH_UNIT_CENTER                 25
#define IDH_UNIT_BUILD                  26
#define IDH_UNIT_REPAIR                 27
#define IDH_UNIT_STOP                   28
#define IDH_UNIT_DESTROY                32
#define IDH_AREA_WIN                    33
#define IDH_AREA_WIN_BUILD              34
#define IDH_AREA_WIN_MOVE               35
#define IDS_CREATE_CHOOSE               36
#define IDS_CREATE_CREATE               37
#define IDH_WORLD_WIN                   38
#define IDS_CREATE_PUBLISH              45
#define IDS_JOIN_PUBLISH                46
#define IDS_JOIN_JOIN                   47
#define IDS_JOIN_AI_0                   48
#define IDS_JOIN_AI_1                   49
#define IDS_JOIN_AI_2                   50
#define IDS_JOIN_AI_3                   51
#define IDS_JOIN_SIZE_0                 52
#define IDS_JOIN_SIZE_1                 53
#define IDS_JOIN_SIZE_2                 54
#define IDS_CREATE_NUM_PLAYERS          55
#define IDS_JOIN1_TITLE                 56
#define IDS_JOIN1_TITLE_SEL             57
#define IDS_JOIN_UNJOIN                 59
#define IDS_CREATE_WORLD                60
#define IDS_MSG_UNIT_GOTO               63
#define IDS_MSG_NET_GOODBYE             64
#define IDS_AI_NAME                     66
#define IDS_LOAD_TERRAIN                67
#define IDS_LOAD_STRUCTURES             68
#define IDS_LOAD_TRANSPORTS             69
#define IDS_CREATE_WINDOWS              70
#define IDS_ALLOC_MAP                   71
#define IDS_INIT_MAP                    72
#define IDS_CHECK_MAP                   73
#define IDS_ASSIGN_TILES                74
#define IDH_AREA_WIN_RMB                75
#define IDS_TIME_OUT                    76
#define IDS_MULT_INST                   77
#define IDH_WORLD_WIN_RMB               78
#define IDS_LOAD_FILE                   79
#define IDS_SAVE_CLOSE                  80
#define IDD_MAIN                        101
#define IDI_MAIN                        102
#define IDA_SAVE                        102
#define IDD_VERSION                     103
#define IDA_CLOSE                       103
#define IDA_CLOSE_APP                   103
#define IDD_JOIN_PUBLISH                105
#define IDA_WORLD                       105
#define IDA_AREA                        106
#define IDC_BAR_AREA                    107
#define IDA_MAIL                        107
#define IDC_AREA_CLOCK                  108
#define IDC_BAR_WORLD                   108
#define IDD_BUILD_STRUCTURE             108
#define IDA_HELP                        108
#define IDC_AREA_COUNTER                109
#define IDC_BAR_CHAT                    109
#define IDD_BUILD_TRANSPORT             109
#define IDA_BOSS                        109
#define IDC_AREA_ZOOM_IN                110
#define IDC_BAR_ADVISOR                 110
#define IDA_OPTIONS                     110
#define IDC_AREA_ZOOM_OUT               111
#define IDC_BAR_VEHICLES                111
#define IDD_JOIN_GAME                   111
#define IDA_RESEARCH                    111
#define IDC_BAR_BUILDINGS               112
#define IDA_DIPLOMAT                    112
#define IDC_BAR_SPYING                  114
#define IDA_RESOURSES                   114
#define IDC_BAR_FILE                    115
#define IDA_TOPO                        115
#define IDC_WORLD_UNITS                 116
#define IDA_ENEMY                       116
#define IDC_WORLD_TOPO                  117
#define IDC_WORLD_RES                   118
#define IDA_UNITS                       118
#define IDC_WORLD_OWNER                 119
#define IDA_CENTER                      119
#define IDC_CHAT_CHAT                   120
#define IDA_BUILD                       120
#define IDC_CHAT_SEND                   121
#define IDA_UNLOAD                      121
#define IDC_CHAT_REPLY                  122
#define IDA_DESELECT                    122
#define IDC_CHAT_FORWARD                123
#define IDA_ROUTE                       123
#define IDC_CHAT_DELETE                 124
#define IDA_RETREAT                     124
#define IDC_BAR_SCIENCE                 125
#define IDB_CLOSED                      125
#define IDA_SAVE1                       125
#define IDA_SAVE2                       126
#define IDB_MASK                        127
#define IDA_SAVE3                       127
#define IDA_SAVE4                       128
#define IDA_SAVE5                       129
#define IDA_SAVE6                       130
#define IDA_SAVE7                       131
#define IDA_SAVE8                       132
#define IDA_SAVE9                       133
#define IDA_SEL1                        134
#define IDC_UNIT_BUILD                  135
#define IDA_SEL2                        135
#define IDC_UNIT_REPAIR                 136
#define IDA_SEL3                        136
#define IDC_UNIT_STOP                   137
#define IDA_SEL4                        137
#define IDD_CREATE_STATUS               138
#define IDA_SEL5                        138
#define IDA_SEL6                        139
#define IDA_SEL7                        140
#define IDC_SPLIT_VERT                  141
#define IDA_SEL8                        141
#define IDC_SPLIT_HORZ                  142
#define IDA_SEL9                        142
#define IDA_VISIBLE                     143
#define IDB_TOOL_MAIL                   144
#define IDA_BUILDINGS                   144
#define IDD_MAIL_COMPOSE                145
#define IDA_VEHICLES                    145
#define IDC_UNIT_ROUTE                  146
#define IDB_TOOL_MAIL_READ              146
#define IDA_NEXT                        146
#define IDD_DIALOG_RAND                 147
#define IDA_PREV                        147
#define IDB_AREA_CLOCK                  148
#define IDD_CHATBAR                     148
#define IDA_CLOSE_WIN                   148
#define IDB_AREA_COUNTER                149
#define IDA_PAUSE                       149
#define IDB_AREA_ZOOM_IN                150
#define IDA_DESTROY                     150
#define IDB_AREA_ZOOM_OUT               151
#define IDA_CUR_LEFT                    151
#define IDA_CUR_UP                      152
#define IDB_CHAT_MSG                    153
#define IDA_CUR_RIGHT                   153
#define IDB_EMAIL_MSG                   154
#define IDA_CUR_DOWN                    154
#define IDB_EMAIL_READ                  155
#define IDA_OPPO                        155
#define IDB_UNIT_ROUTE                  156
#define IDB_NO_SELECT                   156
#define IDA_HIDE_TOOLBAR                156
#define IDB_PLYR_SELECTED               157
#define IDA_UNHIDE_TOOLBAR              157
#define IDB_VOC_MSG                     158
#define IDA_STOP_DESTROY                158
#define IDD_AI_POS                      159
#define IDH_UNIT_RETREAT                161
#define IDH_UNIT_ROUTE                  161
#define IDC_ROAD_BEGIN                  161
#define IDC_ROAD_BEGIN0                 161
#define IDC_ROAD_SET                    162
#define IDC_ROAD_SET0                   162
#define IDH_BAR_AREA                    163
#define IDH_BAR_WORLD                   164
#define IDD_SCENARIO                    164
#define IDH_BAR_CHAT                    165
#define IDC_TARGET0                     165
#define IDH_BAR_ADVISOR                 166
#define IDD_RELATIONS                   166
#define IDH_BAR_VEHICLES                167
#define IDC_SELECT0                     167
#define IDH_BAR_BUILDINGS               168
#define IDC_GOTO2                       168
#define IDT_MAIL                        169
#define IDH_BAR_SCIENCE                 170
#define IDC_ROUTE                       170
#define IDSB_MAIL                       170
#define IDC_GOTO0                       171
#define IDHC_MAIL                       171
#define IDH_BAR_SPYING                  172
#define IDC_GOTO1                       172
#define IDT_MAIL_READ                   172
#define IDC_UNIT_RESUME                 173
#define IDC_GOTO3                       173
#define IDH_BAR_FILE                    174
#define IDC_UNIT_CANCEL_BUILD           174
#define IDC_UNIT_ROAD                   175
#define IDS_CONSTRUCTION                176
#define IDC_WORLD_VISIBLE               176
#define IDS_PEOPLE                      177
#define IDC_UNIT_CANCEL_REPAIR          177
#define IDS_TIME                        178
#define IDC_TARGET1                     178
#define IDS_OPERATING                   179
#define IDC_TARGET2                     179
#define IDC_UNIT_UNLOAD                 179
#define IDS_POWER                       180
#define IDC_TARGET3                     180
#define IDC_AREA_RES                    180
#define IDC_SELECT1                     181
#define IDS_GAS                         181
#define IDS_START_AI2                   182
#define IDC_SELECT2                     182
#define IDC_SELECT3                     183
#define IDS_FOOD                        183
#define IDC_MOVE                        184
#define IDC_UNIT_RETREAT                184
#define IDS_DAMAGE                      184
#define IDC_MOVE0                       184
#define IDC_WORLD                       185
#define IDC_UNIT_CANCEL_ROAD            185
#define IDS_ROUTE_GOTO                  186
#define IDD_FILE                        186
#define IDS_ROUTE_UNLOAD                187
#define IDD_SAVE_MSG                    187
#define IDS_ROUTE_LOAD                  188
#define IDD_RESEARCH                    188
#define IDS_ROUTE_WAYPOINT              189
#define IDC_LOAD                        189
#define IDS_ROUTE_DELETE                190
#define IDC_UNLOAD                      190
#define IDC_UNLOAD0                     190
#define IDC_AREA_COMBAT                 190
#define IDH_ROUTE_GOTO                  191
#define IDC_REPAIR                      191
#define IDH_ROUTE_UNLOAD                192
#define IDC_NO_REPAIR                   192
#define IDH_ROUTE_LOAD                  193
#define IDD_ADV_OPTIONS                 193
#define IDH_ROUTE_WAYPOINT              194
#define IDH_ROUTE_DELETE                195
#define IDD_CHAT_INIT                   195
#define IDB_UNIT_RESUME                 196
#define IDD_PICK_WAIT                   196
#define IDS_NOT_MY_UNIT                 197
#define IDD_PLYR_STAT                   197
#define IDS_SERVER_QUIT                 198
#define IDD_SELECT_CD                   198
#define IDS_CLIENT_QUIT                 199
#define IDR_ACCEL                       200
#define IDR_WORLD                       201
#define IDD_NET_ADDR                    201
#define IDS_MAIL_SEND                   202
#define IDR_AREA                        202
#define IDS_MAIL_REPLY                  203
#define IDS_MAIL_FORWARD                204
#define IDD_SCENARIO_DESC               204
#define IDS_MAIL_DELETE                 205
#define IDD_RSRCH_FOUND                 205
#define IDS_MAIL_REFUSE                 206
#define IDD_TRUCK                       206
#define IDS_MAIL_CHAT                   207
#define IDD_DIALOG1                     207
#define IDS_MAIL_CHAT_ANS               208
#define IDS_MAIL_VOICE                  209
#define IDS_MAIL_VOICE_ANS              210
#define IDS_MAIL_OPTIONS                211
#define IDS_MAIL_READ                   212
#define IDD_LICENSE                     212
#define IDS_MAIL_PREV                   213
#define IDS_MAIL_NEXT                   214
#define IDD_TEST_SOUNDS                 214
#define IDD_PLYR_LIST                   215
#define IDD_CD_LOC                      216
#define IDC_ROAD_BEGIN1                 217
#define IDC_ROAD_BEGIN2                 218
#define IDC_ROAD_BEGIN3                 219
#define IDC_ROAD_SET1                   220
#define IDD_MSG_STATUS                  221
#define IDC_ROAD_SET2                   221
#define IDS_START_AI1                   222
#define IDD_CREATE_SINGLE               222
#define IDC_ROAD_SET3                   222
#define IDS_MSG_ROCKET_START            223
#define IDD_PICK_RACE                   223
#define IDC_LOAD1                       223
#define IDS_MSG_ROCKET_DONE             224
#define IDD_CREATE_MULTI                224
#define IDC_LOAD2                       224
#define IDS_MSG_ROCKET_WAIT             225
#define IDD_CREATE_PUBLISH              225
#define IDC_LOAD3                       225
#define IDB_UNIT_ROAD                   226
#define IDD_PLAYER_LIST                 226
#define IDC_UNLOAD1                     226
#define IDD_JOIN_PLAYERS                227
#define IDC_UNLOAD2                     227
#define IDS_NAME_TOO_LONG               228
#define IDD_LOAD_RACE                   228
#define IDC_UNLOAD3                     228
#define IDS_DESC_TOO_LONG               229
#define IDD_JOIN_RACE                   229
#define IDS_VPSTARTUP_FAILED            230
#define IDD_OPTIONS                     230
#define IDS_VPCREATE_FAILED             231
#define IDD_PICK_PLAYER                 231
#define IDS_VPENUM_FAILED               232
#define IDD_LOAD_MULTI                  232
#define IDC_MOVE1                       232
#define IDS_VPJOIN_FAILED               233
#define IDD_GPF_DATA                    233
#define IDS_VPSEND_FAILED               234
#define IDD_MODELESS_MSG                234
#define IDS_MSG_JOIN_FAILED             235
#define IDD_REGISTER                    235
#define IDS_COPYRIGHT                   236
#define IDS_COPY0                       236
#define IDC_LOAD0                       236
#define IDS_ARR                         237
#define IDS_COPY1                       237
#define IDC_MOVE3                       237
#define IDS_AI_PLAYER                   238
#define IDC_MOVE5                       238
#define IDS_PREV                        239
#define IDC_MOVE7                       239
#define IDS_UNPUBLISH                   240
#define IDC_MOVE2                       240
#define IDC_MOVE4                       241
#define IDS_POS_MIN_CIV                 242
#define IDC_MOVE6                       242
#define IDS_POS_FULL_CIV                243
#define IDS_POS_MIN_COM                 244
#define IDS_POS_FULL_COM                245
#define IDH_UNIT_RESUME                 246
#define IDH_UNIT_CANCEL                 247
#define IDB_UNIT_CANCEL                 248
#define IDH_UNIT_ROAD                   249
#define IDS_INFO_DAMAGE                 250
#define IDS_ROUTE_OK                    251
#define IDH_ROUTE_OK                    252
#define IDS_CHAT_TITLE                  253
#define IDS_CHAT_STATUS                 254
#define IDS_SAVE_FILTERS                255
#define IDS_SAVE_OLD                    256
#define IDS_SAVE_NAME                   257
#define IDS_SAVE_VER                    258
#define IDS_SAVE_ERROR                  259
#define IDS_LOAD_NAME                   260
#define IDS_LOAD_ERROR                  261
#define IDS_ERR_CREATE                  262
#define IDS_RSRCH_NOTHING               263
#define IDS_RSRCH_TITLE                 264
#define IDS_SINGLE_QUIT                 265
#define IDS_COPY3                       266
#define IDS_JOIN_NEW                    267
#define IDS_JOIN_LOAD                   268
#define IDS_JOIN_INPROGRESS             269
#define IDS_RAND_MISMATCH               270
#define IDS_PICKING_RACE                271
#define IDS_READY_TO_GO                 272
#define IDS_ASK_START                   273
#define IDS_DROP_PLAYER                 274
#define IDS_PICKING_PLAYER              275
#define IDH_AREA_OK_FARM                276
#define IDH_AREA_BAD_FARM               277
#define IDH_AREA_NO_FARM                278
#define IDH_AREA_OK_MINE                279
#define IDH_AREA_BAD_MINE               280
#define IDH_AREA_NO_MINE                281
#define IDS_SAVE_EXT                    282
#define IDH_AREA_COAL                   283
#define IDH_AREA_RES                    283
#define IDH_AREA_IRON                   284
#define IDH_AREA_OIL                    285
#define IDH_AREA_COPPER                 286
#define IDH_UNIT_CANCEL_BUILD           287
#define IDH_UNIT_CANCEL_REPAIR          288
#define IDH_UNIT_CANCEL_DESTROY         289
#define IDH_UNIT_UNLOAD                 290
#define IDB_UNIT_UNLOAD                 291
#define IDB_AREA_COAL                   292
#define IDB_AREA_IRON                   293
#define IDB_AREA_OIL                    294
#define IDB_AREA_COPPER                 295
#define IDH_UNIT_CANCEL_ROAD            296
#define IDH_AREA_WIN_ROAD               297
#define IDH_AREA_WIN_REPAIR             298
#define IDS_ERR_LOAD_1                  302
#define IDS_ERR_LOAD_2                  303
#define IDS_NO_MEMORY                   304
#define IDS_ERR_LOAD_3                  305
#define IDS_ERR_LOAD_4                  306
#define IDS_WRONG_DATA_FILE             306
#define IDS_SAVE_ON_ERROR               311
#define IDS_SAVE_ON_ERROR_FAILED        312
#define IDS_EVENT_CONST_LOC             314
#define IDS_EVENT_CONST_CANT            315
#define IDS_EVENT_CONST_START           316
#define IDS_EVENT_HALTED                317
#define IDS_EVENT_CONST_DONE            318
#define IDS_EVENT_REPAIR_DONE           319
#define IDS_EVENT_ROAD_START            320
#define IDS_EVENT_ROAD_HALTED           321
#define IDS_EVENT_ROAD_DONE             322
#define IDS_EVENT_MANF_HALT             324
#define IDS_EVENT_GOTO_CANT             325
#define IDS_EVENT_BLDG_UNDER            326
#define IDS_EVENT_BLDG_HURTING          327
#define IDS_EVENT_BLDG_DYING            328
#define IDS_EVENT_ATK_TARGET            329
#define IDS_EVENT_ATK_DESTROYED         330
#define IDS_EVENT_HAVE_MAIL             331
#define IDS_EVENT_HAVE_CALL             332
#define IDS_EVENT_RSRCH_DONE            333
#define IDS_EVENT_MINE_EMPTY            334
#define IDS_EVENT_POP_LOW               335
#define IDS_EVENT_GAS_LOW               336
#define IDS_EVENT_FOOD_LOW              337
#define IDS_EVENT_POWER_LOW             338
#define IDS_EVENT_GAS_OUT               339
#define IDS_EVENT_FOOD_OUT              340
#define IDS_EVENT_DEAD                  341
#define IDS_EVENT_LEFT                  342
#define IDS_EVENT_JOINED                343
#define IDS_BUILD_PEOPLE                344
#define IDS_ROUTE_AUTO                  345
#define IDH_ROUTE_AUTO                  346
#define IDS_OPTIONS_ADV                 347
#define IDS_DISCOVERED_NO_TITLE         348
#define IDS_DISCOVERED_TITLE            349
#define IDH_STAT_GAS                    350
#define IDH_STAT_POWER                  351
#define IDH_STAT_PEOPLE                 352
#define IDH_STAT_PEOPLE2                353
#define IDH_STAT_FOOD                   354
#define IDH_STAT_CLOCK                  355
#define IDD_PLAY_FLIC                   356
#define IDS_NO_CHAT1                    356
#define IDS_NO_CHAT2                    357
#define IDD_PAUSE_MSG                   357
#define IDS_NO_SCIENCE                  358
#define IDD_OPTIONS1                    358
#define IDH_AREA_CANT_BUILD             359
#define IDD_FILE1                       359
#define IDH_WORLD_RES                   360
#define IDH_WORLD_OWNER                 361
#define IDH_WORLD_UNITS                 362
#define IDH_WORLD_VIS                   363
#define IDH_WORLD_RES2                  364
#define IDH_WORLD_OWNER2                365
#define IDH_WORLD_UNITS2                366
#define IDH_WORLD_VIS2                  367
#define IDS_STAT_DAMAGE                 368
#define IDS_STAT_CONST                  369
#define IDS_STAT_IDLE                   370
#define IDS_STAT_BUILD                  371
#define IDS_STAT_REPAIR                 372
#define IDS_STAT_APT                    373
#define IDS_STAT_APT2                   374
#define IDS_STAT_OFFICE                 375
#define IDS_STAT_OFFICE2                376
#define IDS_STAT_MINE                   377
#define IDS_STAT_MINERALS               378
#define IDS_STAT_FARM                   379
#define IDS_STAT_POWER                  380
#define IDS_EVENT_LOW_HOUSING           381
#define IDS_EVENT_LOW_OFFICE            382
#define IDS_EVENT_NEW_CRANE             383
#define IDS_EVENT_NEW_TRUCK             384
#define IDS_EVENT_NEW_RELATIONS         385
#define IDS_NO_EMBASSY                  386
#define IDH_AREA_CANT_BLDG_NEXT         387
#define IDH_AREA_CANT_WATER_NEXT        388
#define IDH_AREA_CANT_BLDG_RIVER_NEXT   389
#define IDH_AREA_CANT_VEH_IN_WAY        390
#define IDH_AREA_CANT_ON_WATER          391
#define IDH_AREA_CANT_NO_WATER          392
#define IDH_AREA_CANT_NO_LAND_EXIT      393
#define IDH_AREA_CANT_NO_WATER_EXIT     394
#define IDH_AREA_CANT_TOO_STEEP         395
#define IDS_WORLD_TITLE_MAP             396
#define IDS_WORLD_TITLE_RADAR           397
#define IDH_WORLD_FACE                  398
#define IDS_OK                          399
#define IDS_CANCEL                      400
#define IDS_SAVE                        401
#define IDS_YOU_WON                     402
#define IDS_YOU_LOST                    403
#define IDS_LOADING                     404
#define IDS_LEAVING                     405
#define IDS_BAD_PLAYER_NUM              406
#define IDS_EXIT_GAME                   407
#define IDS_STAT_CARRIER                408
#define IDS_YOU_END_SCENARIO            409
#define IDS_LOAD_TRUCK                  410
#define IDS_PAUSE_CLIENT                411
#define IDS_PAUSE_SERVER                412
#define IDS_EVENT_HPR_TRUCKS            413
#define IDS_EVENT_HPR_NOPICKUP          414
#define IDS_EVENT_HPR_SEAPORTS          415
#define IDS_EVENT_HPR_CARGOSHIP         416
#define IDS_EVENT_HPR_NOREACH           417
#define IDS_STAT_ROCKET                 418
#define IDS_EVENT_CANT_BRIDGE           419
#define IDS_EVENT_HAVE_RADAR            420
#define IDS_ERROR_LOW_PHYS_MEM          421
#define IDS_ERROR_LOW_VIRT_MEM          422
#define IDS_ERROR_LOW_AVAIL_MEM         423
#define IDS_COST                        424
#define IDS_HAVE                        425
#define IDS_NEED                        426
#define IDS_CONTINUE                    427
#define IDS_STAT_MATERIAL               428
#define IDS_ROUTE_TITLE                 429
#define IDS_RESEARCHING                 430
#define IDS_LONGEST_STRING              431
#define IDS_EXHAUSTED                   432
#define IDS_WAYPOINT                    433
#define IDS_LOAD                        434
#define IDS_UNLOAD                      435
#define IDS_EVENT_ROCKET_CANT_LAND      436
#define IDS_LOAD_MUSIC                  437
#define IDS_JOIN_LOAD_FILE              438
#define IDS_JOIN_FILE_ERROR             439
#define IDS_AI_LIMIT_2_MAX              440
#define IDS_AI_LIMIT_MAX                441
#define IDS_BUILDINGS                   442
#define IDS_VEHICLES                    443
#define IDS_PLAYERS                     444
#define IDS_GAME_OVER                   445
#define IDH_MAIL_READ                   446
#define IDH_MAIL_SEND                   447
#define IDH_MAIL_REPLY                  448
#define IDH_MAIL_FORWARD                449
#define IDH_MAIL_DELETE                 450
#define IDH_MAIL_REFUSE                 451
#define IDH_MAIL_CHAT                   452
#define IDH_MAIL_CHAT_ANS               453
#define IDH_MAIL_OPTIONS                454
#define IDS_GIVE_UNITS                  455
#define IDS_NEW_SERVER                  456
#define IDS_EVENT_HPR_NOACCESS          456
#define IDS_LOAD_SFX                    457
#define IDH_AREA_COMBAT                 458
#define IDS_UNKNOWN                     459
#define IDS_LOAD_FREIGHTER              460
#define IDS_BUILD_VEHICLE               461
#define IDS_BUILD_UNIT                  462
#define IDS_TRUCK_AUTO                  463
#define IDS_TRUCK_IDLE                  464
#define IDS_TRUCK_ROUTE                 465
#define IDS_TRUCK_TRAVEL                466
#define IDS_PLYR_TAKEN                  467
#define IDS_ERROR_NT_NET_BUG            468
#define IDS_CANT_SAVE                   469
#define IDS_MAX_CHAT                    470
#define IDS_MAX_MAIL                    471
#define IDS_VDMPLAY_VER                 472
#define IDS_MSS_VER                     473
#define IDS_DEMO_OVER                   474
#define IDS_DEMO_RESEARCH_MAX           475
#define IDS_NONE                        476
#define IDS_YOUR_ADDR                   477
#define IDS_IS_ADDR                     478
#define IDS_EN_VER                      479
#define IDS_VP_VER                      480
#define IDS_DEMO_25                     481
#define IDS_ADDR_OFF                    482
#define IDS_ADDR                        483
#define IDS_ADV_DEPTH                   484
#define IDS_ADV_ZOOM                    485
#define IDS_ERROR_LOW_COLOR_DEPTH       486
#define IDS_ERROR_LOW_COLOR_DEPTH2      487
#define IDS_ERROR_LOW_ZOOM              488
#define IDS_ERROR_LOW_ZOOM2             489
#define IDS_ERROR_LOW_MUSIC             490
#define IDS_HPR_BLOCKED                 491
#define IDS_AI_TAKEOVER                 492
#define IDS_KILLER_RES                  493
#define IDS_SERVER                      494
#define IDS_ERROR_16_BIT_WARNING        495
#define IDS_ERROR_MULT_PROT_WARNING     496
#define IDS_SAVE_REMOTE                 497
#define IDS_SAVE_LOCAL                  498
#define IDS_SAVE_DATA                   499
#define IDS_SAVE_COMPRESS               500
#define IDS_SAVE_WRITE                  501
#define IDS_OUT_OF_MEMORY               502
#define IDS_WORLD_NE                    503
#define IDS_WORLD_SE                    504
#define IDS_WORLD_SW                    505
#define IDS_WORLD_NW                    506
#define IDS_BAD_REG                     507
#define IDS_GOOD_REG                    508
#define IDS_EN_LOGGING                  509
#define IDS_VP_LOGGING                  510
#define IDC_MAIN_CREATE                 1000
#define IDC_MAIN_JOIN                   1001
#define IDC_MAIN_LOAD                   1002
#define IDC_HANGUP                      1002
#define IDC_MAIN_CREDITS                1003
#define IDC_SELECTPLAYER                1003
#define IDC_MAIN_LOAD_MUL               1004
#define IDC_MAIN_OPTIONS                1006
#define IDC_MAIN_INTRO                  1007
#define IDC_VER_TEXT                    1008
#define IDC_CREATE_NAME                 1009
#define IDC_VER_TEXT_OS                 1009
#define IDC_CREATE_TCPIP                1011
#define IDC_CREATE_IPX                  1012
#define IDC_CREATE_NETBIOS              1013
#define IDC_CREATE_DIRECTPLAY           1014
#define IDC_CREATE_MODEM                1015
#define IDC_CREATE_TAPI                 1016
#define IDC_CREATE_DIRECT               1017
#define IDC_CREATE_NUM_AI               1020
#define IDC_CREATE_EASY                 1026
#define IDC_CREATE_MODERATE             1027
#define IDC_CREATE_DIFFICULT            1028
#define IDC_CREATE_IMPOSSIBLE           1029
#define IDC_CREATE_SMALL                1030
#define IDC_CREATE_MEDIUM               1031
#define IDC_CREATE_LARGE                1032
#define IDC_CREATE_NUM_PLAYERS          1033
#define IDC_CREATE_LIST                 1034
#define IDC_RACE_LIST                   1038
#define IDC_RACE_DESC                   1042
#define IDC_RACE_NAME                   1053
#define IDC_JOIN_GAMES                  1055
#define IDC_JOIN_NAME                   1056
#define IDC_JOIN_GAMES_PRMT             1060
#define IDC_JOIN_PREV                   1062
#define IDC_BUILD_LIST                  1070
#define IDC_BUILD_TEXT                  1071
#define IDC_BUILD_LIST_BLDGS            1072
#define IDC_BUILD_PICTURE               1073
#define IDC_JOIN_NUM_OPPONENTS          1078
#define IDC_JOIN_AI_LEVEL               1079
#define IDC_JOIN_WORLD_SIZE             1080
#define IDC_JOIN_DESC                   1081
#define IDC_JOIN_NO_MORE                1082
#define IDC_JOIN_UNTIL_COLONIZE         1083
#define IDC_JOIN_FINAL_APPROVAL         1084
#define IDC_CREATE_DELETE_PLAYER        1087
#define IDC_JOIN_SERVER                 1088
#define IDC_UNPUBLISH                   1089
#define IDC_CREATE_DESC                 1090
#define IDC_JOIN_UNPUBLISH              1091
#define IDC_CREATE_WAIT_TEXT            1093
#define IDC_PER_BAR                     1094
#define IDC_VER_NET                     1095
#define IDC_VER_THUNK                   1096
#define IDC_BUILD_MATERIALS             1097
#define IDC_VER_RIF                     1097
#define IDC_VER_VIDEO                   1098
#define IDC_VER_SOUND                   1099
#define IDC_VER_SOUND2                  1100
#define IDC_VER_SPEED                   1101
#define IDC_VER_MEMORY                  1102
#define IDC_MAIL_TO                     1117
#define IDC_MAIL_SUBJECT                1118
#define IDC_MAIL_TEXT                   1119
#define IDC_RAND_EDIT                   1120
#define IDC_PLAYER_LIST                 1121
#define IDC_IGNORE_EMAIL                1122
#define IDC_ACCEPT_EMAIL                1123
#define IDC_IGNORE_CHAT                 1124
#define IDC_ACCEPT_CHAT                 1125
#define IDC_IGNORE_VOICE                1126
#define IDC_ACCEPT_VOICE                1127
#define IDC_LIST_AI                     1128
#define IDC_MAIN_SINGLE                 1132
#define IDC_PLAY_POS_0                  1136
#define IDC_PLAY_POS_1                  1137
#define IDC_PLAY_POS_2                  1138
#define IDC_RACE_PREV                   1138
#define IDC_PLAY_POS_3                  1139
#define IDC_CREATE_ADV                  1148
#define IDC_JOIN_POS                    1156
#define IDC_JOIN_TYPE                   1157
#define IDC_REL_LIST                    1159
#define IDC_RSRCH_LIST                  1159
#define IDC_PLYR_ALLIANCE               1160
#define IDC_PLYR_PEACE                  1161
#define IDC_PLYR_NEUTRAL                1162
#define IDC_PLYR_HOSTILE                1163
#define IDC_PLYR_WAR                    1164
#define IDC_MAIN_CAMPAIGN               1165
#define IDC_BUILD_LIST_CAT              1166
#define IDC_FILE_SAVE                   1167
#define IDC_FILE_LOAD                   1168
#define IDC_FILE_SPEED                  1169
#define IDC_FILE_HELP                   1171
#define IDC_FILE_EXIT                   1172
#define IDC_FILE_SOUND                  1173
#define IDC_SAVE_NAME                   1173
#define IDC_FILE_MUSIC                  1174
#define IDC_FILE_MINIMIZE               1175
#define IDC_FILE_ADV                    1175
#define IDC_RSRCH_DESC                  1176
#define IDC_RSRCH_PROGRESS              1177
#define IDC_CREATE_PLAYER               1178
#define IDC_CREATE_PW                   1179
#define IDC_LOAD_PREV                   1182
#define IDC_LOAD_SINGLE                 1183
#define IDC_FILE_VERSION                1184
#define IDC_ADV_BLT                     1185
#define IDC_RADIO2                      1186
#define IDC_RADIO3                      1187
#define IDC_RADIO4                      1188
#define IDC_RADIO5                      1189
#define IDC_ADV_ZOOM                    1190
#define IDC_RADIO7                      1191
#define IDC_CHAT_RCV                    1191
#define IDC_ADV_ZOOM_1                  1191
#define IDC_RADIO8                      1192
#define IDC_ADV_ZOOM_3                  1192
#define IDC_ADV_MUSIC                   1193
#define IDC_BUILD_NUM                   1193
#define IDC_ADV_ZOOM3                   1194
#define IDC_BUILD_SPIN                  1194
#define IDC_ADV_MUSIC_1                 1194
#define IDC_ADV_ZOOM4                   1195
#define IDC_STAT_NAME                   1195
#define IDC_ADV_MUSIC_2                 1195
#define IDC_STAT_GAS                    1196
#define IDC_BROWSE                      1196
#define IDC_STAT_POWER                  1197
#define IDC_SEL_MSG                     1197
#define IDC_STAT_FOOD                   1198
#define IDC_STAT_PEOPLE                 1199
#define IDC_NET_ADDRESS                 1199
#define IDC_NET_ADDR                    1201
#define IDC_SCENE_DESC                  1202
#define IDC_RSRCH_FOUND                 1203
#define IDC_TEXT_DISCOVERY              1204
#define IDC_RSRCH_STAT                  1205
#define IDC_USER1                       1206
#define IDC_SCENE_SAVE                  1207
#define IDC_FILE_SCENE                  1208
#define IDC_OPT_SCROLL                  1209
#define IDC_OPT_LANG                    1210
#define IDC_NUM_PRMT                    1211
#define IDC_OPT_PAUSE                   1211
#define IDC_TRUCK_LUMBER                1212
#define IDC_TRUCK_SPIN_LUMBER           1213
#define IDC_TRUCK_STEEL                 1214
#define IDC_TRUCK_SPIN_STEEL            1215
#define IDC_TRUCK_XILITIUM              1216
#define IDC_TRUCK_SPIN_XILITIUM         1217
#define IDC_TRUCK_COAL                  1218
#define IDC_TRUCK_SPIN_COAL             1219
#define IDC_TRUCK_IRON                  1220
#define IDC_TRUCK_SPIN_IRON             1221
#define IDC_TRUCK_OIL                   1222
#define IDC_TRUCK_SPIN_OIL              1223
#define IDC_TRUCK_UNLOAD                1224
#define IDC_TRUCK_LOAD_BLDG             1225
#define IDC_TRUCK_LOAD_VEH              1226
#define IDC_TRUCK_AUTO                  1227
#define IDC_TRUCK_LOAD                  1228
#define IDC_LICENSE                     1229
#define IDC_PAUSE_TEXT                  1230
#define IDC_SFX_TYP_MIDI                1231
#define IDC_SFX_TYP_MIDI2               1232
#define IDC_SFX_TYP_MIDI3               1233
#define IDC_SFX_GROUP                   1234
#define IDC_SFX_GROUP2                  1235
#define IDC_SFX_GROUP3                  1236
#define IDC_SFX_FORMAT                  1237
#define IDC_SFX_DESC                    1238
#define IDC_SFX_TRACK                   1239
#define IDC_PLAY_FORE                   1240
#define IDC_PLAY_BACK                   1241
#define IDC_TRUCK_HAVE_LUMBER           1241
#define IDC_PLAY_EXCL                   1242
#define IDC_TRUCK_HAVE_STEEL            1242
#define IDC_PLAY_SHUTUP                 1243
#define IDC_TRUCK_HAVE_XIL              1243
#define IDC_TRUCK_HAVE_COAL             1244
#define IDC_TRUCK_HAVE_IRON             1245
#define IDC_TRUCK_HAVE_OIL              1246
#define IDC_TRUCK_MAX                   1247
#define IDC_ADV_DEPTH_0                 1248
#define IDC_ADV_DEPTH_1                 1249
#define IDC_PLYR_KILL                   1249
#define IDC_ADV_DEPTH_2                 1250
#define IDC_PLYR_PAUSE                  1250
#define IDC_PLYR_OPTIONS                1251
#define IDC_PLYR_MINIMIZE               1252
#define IDC_PLYR_LIST                   1253
#define IDC_PLYR_TAKE_OVER              1254
#define IDC_PLYR_PASSWORD               1255
#define IDC_PLYR_GIVE                   1256
#define IDC_CD_DRIVES                   1257
#define IDC_CD_STAT                     1258
#define IDC_ADV_ZOOM_2                  1260
#define IDC_PLYR_ADDR                   1262
#define IDC_PLYR_IS_ADDR                1263
#define IDC_PLYR_VP_VER                 1264
#define IDC_PLYR_EN_VER                 1265
#define IDC_PLYR_DO_ADDR                1266
#define IDC_COPY_STACK                  1274
#define IDC_STACK_DUMP                  1275
#define IDC_ADV_RES_NATIVE              1276
#define IDC_ADV_RES_SPEED               1277
#define IDC_ADV_RES_640                 1278
#define IDC_ADV_RES_800                 1279
#define IDC_ADV_RES_1024                1280
#define IDC_ADV_NO_INTRO                1281
#define IDC_ADV_USE_SYS_COLORS          1282
#define IDC_SAVE_STATUS                 1283
#define IDS_MSG                         1284
#define IDC_REG_DONE                    1287

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         159
#define _APS_NEXT_CONTROL_VALUE         1288
#define _APS_NEXT_SYMED_VALUE           191
#endif
#endif
