#ifndef ___WINDWRD_H__
#define ___WINDWRD_H__


//---------------------------------------------------------------------------
//
//	Copyright (c) 1995, 1996. Windward Studios, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------


// this is always defined in windward so it's there for the apps
#define _LOGOUT

#include <windward.h>

// needed by some
extern CWinApp * ptheApp;



#endif
